### ISSUE TITLE
Bug? Incoming Garbage to a fire station

### ISSUE THREAD

**Issue by originalfoo** [algernon-A/TransferController#10]
Not sure if I'm just reading it wrong, but this fire station looks like it's had offers for incoming garbage?

![image](https://user-images.githubusercontent.com/1386719/168185474-aa2b0e7a-51bc-4ef9-8fd4-d152ae27c63a.png)

Also, what does `Allow None`  and the numbers mean? eg. `Fire Out 3-7: 25520-32057: Allow None`?

**Comment by algernon-A** [comment]
Not a bug, but a not-very-intuitive line.  "In" in this case means the offer was matched from an incoming offer - so the match was made while the incoming offer was being processed (this is significant in terms of bug tracking, but meaningless to most people).

The numbers are the transfer priorities (e.g. 3-7) and the building IDs (e.g. 25520-32057), both listed in the order incoming, outgoing for each match, the "allow" means that the match wasn't blocked by any mod settings ("Deny" would be displayed otherwise).  The last word is the reason for the "Deny" (which is just "none" if the transfer was allowed).

I'll be changing the log line format to make it more intuitive to casual users, not just me.

**Comment by algernon-A** [comment]
Text changed in d6a3424f4495a51289c0ab69d38a430ea2b9e090
